"""outbox

Revision ID: 26f5351f3468
Revises: f843ccc6d36c
Create Date: 2026-04-15 08:51:06.838410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f5351f3468'
down_revision: Union[str, Sequence[str], None] = 'f843ccc6d36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('payload', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'payload')
    # ### end Alembic commands ###
