"""payment field

Revision ID: a0f5ebc69669
Revises: 26f5351f3468
Create Date: 2026-04-15 10:56:43.432686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f5ebc69669'
down_revision: Union[str, Sequence[str], None] = '26f5351f3468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('acquiring_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'acquiring_data')
    # ### end Alembic commands ###
